-- ================================================================
-- SQL DDL TEMPLATE (TOPIC 04)
-- ================================================================
-- WHAT SHOULD BE ADDED HERE:
-- 1) Full PostgreSQL DDL for your finalized schema.
-- 2) CREATE TABLE statements for all entities from your ER diagram.
-- 3) Primary keys, foreign keys, NOT NULL, UNIQUE, CHECK constraints.
-- 4) Indexes for important search/join columns.
-- 5) Clean structure and comments (group by tables/constraints/indexes).
--
-- RECOMMENDED ORDER:
-- 1) Tables
-- 2) Constraints (if not inline)
-- 3) Indexes
--
-- TEAM NOTE:
-- Add short attribution comments for who implemented which part.
-- Example:
-- [Name] - users, roles, permissions tables
-- [Name] - orders, payments, invoices tables
--
-- IMPORTANT:
-- The script must run in PostgreSQL and produce a working schema that
-- matches your approved ER diagram and conceptual schema.
-- Submit this as one SQL file.

-- ================================================================

-- =========================================================
-- 1. TABLES & CONSTRAINTS
-- =========================================================

-- [Yaroslav Kvachuk] Physical address of a restaurant location.
Create Table restaurantschema."Locations"(
	LocationId Int Generated By Default As Identity Primary Key,
	Address Varchar(255) Not Null
);

-- [Yaroslav Kvachuk] Main restaurant entity.
Create Table restaurantschema."Restaurants"(
	RestaurantId Int Generated By Default As Identity Primary Key,
	Name Varchar(100) Not Null,
	Rating Int,
	LocationId Int Unique,

	Constraint fk_restaurant_location Foreign Key (LocationId)
		References restaurantschema."Locations"(LocationId)
		On Delete Set Null,
    Constraint chk_restaurant_rating Check (Rating Between 1 And 5)
);

-- [Vitaliy Balia] Lookup table of staff roles.
Create Table restaurantschema."StaffRoles"(
	StaffRoleId Int Generated By Default As Identity Primary Key,
	RoleName Varchar(50) Not Null Unique,
	Description Varchar(255)
);

-- [Vitaliy Balia] Employees information.
Create Table restaurantschema."Staff"(
	StaffId Int Generated By Default As Identity Primary Key,
	StaffRoleId Int,
	Name Varchar(100) Not Null,
	Address Varchar(255),
	Phone Varchar(35),

	Constraint fk_staff_role Foreign Key (StaffRoleId)
		References restaurantschema."StaffRoles"(StaffRoleId)
		On Delete Set Null
);

-- [Ihor Zinchenko] M:N assignment of staff to restaurants.
Create Table restaurantschema."StaffRestaurantJunctionTable"(
	StaffId Bigint,
	RestaurantId Bigint,

	Primary Key (StaffId, RestaurantId),

	Constraint fk_staffrest_staff Foreign Key (StaffId)
		References restaurantschema."Staff"(StaffId)
		On Delete Cascade,

	Constraint fk_staffrest_restaurant Foreign Key (RestaurantId)
		References restaurantschema."Restaurants"(RestaurantId)
		On Delete Cascade
);

-- [Ihor Zinchenko] Work shift scheduling logic.
Create Table restaurantschema."ShiftSchedules_JunctionTable"(
	ShiftScheduleId Bigint Generated By Default As Identity Primary Key,
	StaffId Bigint Not Null,
	RestaurantId Bigint Not Null,
	StartDateTime Timestamp Not Null,
	EndDateTime Timestamp Not Null,

	Constraint fk_shift_staff Foreign Key (StaffId)
		References restaurantschema."Staff"(StaffId)
		On Delete Cascade,

	Constraint fk_shift_restaurant Foreign Key (RestaurantId)
		References restaurantschema."Restaurants"(RestaurantId)
		On Delete Cascade,

	Constraint chk_shift_dates Check (EndDateTime > StartDateTime)
);

-- [Ihor Zinchenko] Categories for the menu.
Create Table restaurantschema."MenuItemCategory"(
	CategoryId Int Generated By Default As Identity Primary Key,
	CategoryName Varchar(30) Not Null
);

-- [Ihor Zinchenko] Detailed menu items.
Create Table restaurantschema."MenuItems"(
	MenuItemId Bigint Generated By Default As Identity Primary Key,
	Name Varchar(100) Not Null,
	Description Varchar(255),
	Weight Numeric(6,2),
	Price Numeric(10,2) Not Null,
	CategoryId Int,

	Constraint fk_menuitem_category Foreign Key (CategoryId)
		References restaurantschema."MenuItemCategory"(CategoryId)
		On Delete Set Null,
    Constraint chk_menu_price Check (Price >= 0)
);

-- [Ihor Zinchenko] Availability of menu items per restaurant.
Create Table restaurantschema."RestaurantMenuItemsJunctionTable"(
	RestaurantId Bigint,
	MenuItemId Bigint,

	Primary Key (RestaurantId, MenuItemId),

	Constraint fk_restmenu_restaurant Foreign Key (RestaurantId)
		References restaurantschema."Restaurants"(RestaurantId)
		On Delete Cascade,

	Constraint fk_restmenu_menuitem Foreign Key (MenuItemId)
		References restaurantschema."MenuItems"(MenuItemId)
		On Delete Cascade
);

-- [Ihor Zinchenko] Ingredients master data.
Create Table restaurantschema."Ingredients"(
	IngredientId Int Generated By Default As Identity Primary Key,
	Name Varchar(100) Not Null,
	Weight Numeric(6,2),
	Quantity Int Default 0
);

-- [Ihor Zinchenko] Recipe composition (M:N).
Create Table restaurantschema."MenuItemIngredientsJunctionTable"(
	ElementId Int Generated By Default As Identity Primary Key,
	MenuItemId Bigint Not Null,
	IngredientId Int Not Null,

	Constraint fk_menuingr_menuitem Foreign Key (MenuItemId)
		References restaurantschema."MenuItems"(MenuItemId)
		On Delete Cascade,

	Constraint fk_menuingr_ingredient Foreign Key (IngredientId)
		References restaurantschema."Ingredients"(IngredientId)
		On Delete Restrict,

	Constraint uq_menuingr_pair Unique (MenuItemId, IngredientId)
);

-- [Ihor Zinchenko] Inventory management.
Create Table restaurantschema."BasicInventories"(
	BasicInventoryId Int Generated By Default As Identity Primary Key,
	IngredientId Int,
	Name Varchar(50),
	Count Bigint Default 0,

	Constraint fk_inventory_ingredient Foreign Key (IngredientId)
		References restaurantschema."Ingredients"(IngredientId)
		On Delete Set Null
);

-- [Maksym Belei] Inventory tracking across locations.
Create Table restaurantschema."RestaurantInventoryJunctionTable"(
	ElementId Int Generated By Default As Identity Primary Key,
	RestaurantId Bigint Not Null,
	BasicInventoryId Bigint Not Null,

	Constraint fk_restinv_restaurant Foreign Key (RestaurantId)
		References restaurantschema."Restaurants"(RestaurantId)
		On Delete Cascade,

	Constraint fk_restinv_inventory Foreign Key (BasicInventoryId)
		References restaurantschema."BasicInventories"(BasicInventoryId)
		On Delete Cascade,

	Constraint uq_restinv_pair Unique (RestaurantId, BasicInventoryId)
);

-- [Maksym Belei] Goods Suppliers.
Create Table restaurantschema."Suppliers"(
	SupplierId Int Generated By Default As Identity Primary Key,
	Name Varchar(100) Not Null,
	Address Varchar(255),
	Phone Varchar(35)
);

-- [Maksym Belei] Supplier links to inventory.
Create Table restaurantschema."BasicInventoriesSuppliersJunctionTable"(
	SupplierId Bigint,
	BasicInventoryId Bigint,

	Primary Key (SupplierId, BasicInventoryId),

	Constraint fk_invsup_supplier Foreign Key (SupplierId)
		References restaurantschema."Suppliers"(SupplierId)
		On Delete Cascade,

	Constraint fk_invsup_inventory Foreign Key (BasicInventoryId)
		References restaurantschema."BasicInventories"(BasicInventoryId)
		On Delete Cascade
);

-- [Yaroslav Kvachuk] Physical restaurant tables.
Create Table restaurantschema."RestaurantTables"(
	TableId Int Generated By Default As Identity Primary Key,
	RestaurantId Bigint Not Null,
	SizeOfTable Int Not Null,

	Constraint fk_table_restaurant Foreign Key (RestaurantId)
		References restaurantschema."Restaurants"(RestaurantId)
		On Delete Cascade,
    Constraint chk_table_size Check (SizeOfTable > 0)
);

-- [Davyd Vlasov] Customers entity.
Create Table restaurantschema."Customers"(
	CustomerId Int Generated By Default As Identity Primary Key,
	Name Varchar(100) Not Null,
	Phone Varchar(35)
);

-- [Davyd Vlasov] Booking system implementation.
Create Table restaurantschema."Reservations"(
	ReservationId Int Generated By Default As Identity Primary Key,
	TableId Bigint Not Null,
	CustomerId Bigint Not Null,
	ReservationDateTime Timestamp Not Null,
	NumberOfPeople Int Not Null,

	Constraint fk_reservation_table Foreign Key (TableId)
		References restaurantschema."RestaurantTables"(TableId)
		On Delete Restrict,

	Constraint fk_reservation_customer Foreign Key (CustomerId)
		References restaurantschema."Customers"(CustomerId)
		On Delete Restrict,

	Constraint chk_reservation_people Check (NumberOfPeople > 0)
);

-- [Davyd Vlasov] Customer feedback management.
Create Table restaurantschema."CustomerFeedbacks"(
	FeedbackId Int Generated By Default As Identity Primary Key,
	CustomerId Bigint Not Null,
	RestaurantId Bigint Not Null,
	Rating Int Not Null,
	Comment Varchar(500),

	Constraint fk_feedback_customer Foreign Key (CustomerId)
		References restaurantschema."Customers"(CustomerId)
		On Delete Restrict,

	Constraint fk_feedback_restaurant Foreign Key (RestaurantId)
		References restaurantschema."Restaurants"(RestaurantId)
		On Delete Cascade,

	Constraint chk_feedback_rating Check (Rating Between 1 And 5)
);

-- [Ihor Zinchenko] Lookup for order types.
Create Table restaurantschema."OrderTypes"(
	OrderTypeId Int Generated By Default As Identity Primary Key,
	NameOfType Varchar(30) Not Null Unique
);

-- [Ihor Zinchenko] Orders tracking.
Create Table restaurantschema."Orders"(
	OrderId Int Generated By Default As Identity Primary Key,
	TableId Bigint,
	OrderTypeId Bigint Not Null,
	CustomerId Bigint Not Null,
	Status Varchar(20) Default 'pending',

	Constraint fk_order_table Foreign Key (TableId)
		References restaurantschema."RestaurantTables"(TableId)
		On Delete Set Null,

	Constraint fk_order_ordertype Foreign Key (OrderTypeId)
		References restaurantschema."OrderTypes"(OrderTypeId)
		On Delete Restrict,

	Constraint fk_order_customer Foreign Key (CustomerId)
		References restaurantschema."Customers"(CustomerId)
		On Delete Restrict
);

-- [Ihor Zinchenko] Junction for order line items.
Create Table restaurantschema."MenuItems_Orders_JunctionTable"(
	MenuItemId Bigint,
	OrderId Int,

	Primary Key (MenuItemId, OrderId),

	Constraint fk_menuorder_menuitem Foreign Key (MenuItemId)
		References restaurantschema."MenuItems"(MenuItemId)
		On Delete Restrict,

	Constraint fk_menuorder_order Foreign Key (OrderId)
		References restaurantschema."Orders"(OrderId)
		On Delete Restrict
);


-- =========================================================
-- 2. INDEXES (Optimized by Ihor Zinchenko)
-- =========================================================

Create Index idx_staffrest_restaurant On restaurantschema."StaffRestaurantJunctionTable"(RestaurantId);
Create Index idx_restmenu_menuitem On restaurantschema."RestaurantMenuItemsJunctionTable"(MenuItemId);
Create Index idx_restinv_inventory On restaurantschema."RestaurantInventoryJunctionTable"(BasicInventoryId);
Create Index idx_invsup_inventory On restaurantschema."BasicInventoriesSuppliersJunctionTable"(BasicInventoryId);
Create Index idx_menuorder_order On restaurantschema."MenuItems_Orders_JunctionTable"(OrderId);
Create Index idx_menuingr_ingredient On restaurantschema."MenuItemIngredientsJunctionTable"(IngredientId);
Create Index idx_shift_staff On restaurantschema."ShiftSchedules_JunctionTable"(StaffId);
Create Index idx_shift_restaurant On restaurantschema."ShiftSchedules_JunctionTable"(RestaurantId);
Create Index idx_inventory_ingredient On restaurantschema."BasicInventories"(IngredientId);
Create Index idx_reservation_customer On restaurantschema."Reservations"(CustomerId);
Create Index idx_reservation_table On restaurantschema."Reservations"(TableId);
Create Index idx_feedback_restaurant On restaurantschema."CustomerFeedbacks"(RestaurantId);
Create Index idx_orders_customer On restaurantschema."Orders"(CustomerId);


